### ISSUE TITLE
select a default value

### ISSUE THREAD

**Issue by bryandellinger** [Supertext/knockout.groupedOptions#6]
just wondering how to set a default value?  for instance in your examples if I wanted the default value to be "1-3" how would I do that?

**Comment by awj100** [comment]
By "Set a default value" I presume you mean _pre-select a value_.

In this case, as with every observable - or more generally, MVVM - you can pre-select a value by assigning a value to the bound observable. Thus, when the observable is bound to the UI it already contains a value rather than waiting for the user to indicate a value.

[This fiddle](http://jsfiddle.net/ajameson/c8q4e053/3/) demonstrates this - look at lines 57-60.

**Comment by tnixon01** [comment]
Update: I figured it out. Just leave groupedOption's value unspecified, and use the regular Knockout value binding -- this will two-way bind to the (html) value of the option.

-- original question --
Does this not provide a mechanism to pre-select an option based on just the (single property) value, rather than the entire object? That is, do I need to provide {Text: 'item 1-3', Value: '1-3'}, instead of just providing "1-3" (likely a key from my underlying database)?

I wanted to make sure I understand and am using it correctly, and not missing something, because it seems like a long extra step that's kind of out of line from how the similar functionality works in the knockout/select/value binding.

Thanks! This has proven so far to be a great tool for me!
